name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: ./Scripts/lint.sh
      - name: Build
        run: swift build
      - name: Test
        run: swift test --enable-xctest --disable-swift-testing
